# Generated by Django 5.2.17 on 2026-08-15 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Sistem Yöneticisi (Admin)'), ('OPERATOR', 'Operatör'), ('READ_ONLY', 'Salt Okunur (Read Only)'), ('AUDITOR', 'Denetçi (Auditor)')], db_index=True, default='OPERATOR', max_length=20, verbose_name='Kullanıcı Rolü')),
                ('personnel_number', models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='Sicil Numarası')),
                ('department', models.CharField(blank=True, default='', max_length=100, verbose_name='Departman / Birim')),
                ('phone_number', models.CharField(blank=True, default='', max_length=20, verbose_name='Dahili / Telefon')),
                ('theme_preference', models.CharField(choices=[('light', 'Açık Tema'), ('dark', 'Koyu Tema')], default='light', max_length=10, verbose_name='Tema Tercihi')),
                ('last_activity', models.DateTimeField(blank=True, null=True, verbose_name='Son Aktivite Zamanı')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Son Giriş IP')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Kullanıcı Profili',
                'verbose_name_plural': 'Kullanıcı Profilleri',
                'ordering': ['-user__date_joined'],
            },
        ),
    ]
