# Generated by Django 5.2.17 on 2026-08-15 21:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Cihaz ID')),
                ('personnel_number', models.CharField(db_index=True, help_text='Cihazın zimmetli olduğu personel sicil numarası', max_length=50, unique=True, verbose_name='Sicil Numarası')),
                ('hostname', models.CharField(db_index=True, max_length=100, verbose_name='Bilgisayar Adı / Hostname')),
                ('display_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Görünen İsim')),
                ('operating_system', models.CharField(choices=[('WINDOWS', 'Windows'), ('LINUX', 'Linux')], db_index=True, default='WINDOWS', max_length=20, verbose_name='İşletim Sistemi')),
                ('os_version', models.CharField(blank=True, default='', max_length=100, verbose_name='İşletim Sistemi Sürümü')),
                ('ip_address', models.GenericIPAddressField(db_index=True, verbose_name='IP Adresi')),
                ('mac_address', models.CharField(blank=True, default='', max_length=30, verbose_name='MAC Adresi')),
                ('username', models.CharField(max_length=100, verbose_name='Bağlantı Kullanıcı Adı')),
                ('domain', models.CharField(blank=True, default='', max_length=100, verbose_name='Etki Alanı / Domain')),
                ('connector_type', models.CharField(choices=[('WINDOWS_REMOTE', 'Windows Remote Management'), ('SSH', 'SSH / SFTP'), ('SFTP', 'SFTP Direct'), ('MOCK', 'Geliştirme / Mock Connector')], default='SSH', max_length=30, verbose_name='Bağlantı Türü')),
                ('port', models.PositiveIntegerField(default=22, verbose_name='Bağlantı Portu')),
                ('status', models.CharField(choices=[('ONLINE', 'Çevrimiçi'), ('OFFLINE', 'Çevrimdışı'), ('WARNING', 'Uyarı'), ('UNKNOWN', 'Bilinmiyor')], db_index=True, default='UNKNOWN', max_length=20, verbose_name='Cihaz Durumu')),
                ('last_seen', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Son Görülme Zamanı')),
                ('description', models.TextField(blank=True, default='', verbose_name='Açıklama / Notlar')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kayıt Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Son Güncelleme')),
            ],
            options={
                'verbose_name': 'Yetkili Cihaz',
                'verbose_name_plural': 'Yetkili Cihazlar',
                'ordering': ['hostname', 'personnel_number'],
                'indexes': [models.Index(fields=['personnel_number', 'hostname'], name='devices_dev_personn_4acf4c_idx'), models.Index(fields=['status', 'operating_system'], name='devices_dev_status_34ce26_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credential_type', models.CharField(choices=[('PASSWORD', 'Parola'), ('SSH_KEY', 'SSH Özel Anahtarı'), ('TOKEN', 'Kimlik Doğrulama Belirteci')], default='PASSWORD', max_length=20, verbose_name='Kimlik Bilgisi Türü')),
                ('_encrypted_secret', models.TextField(blank=True, db_column='encrypted_secret', default='', verbose_name='Şifrelenmiş Parola/Anahtar')),
                ('ssh_key_path', models.CharField(blank=True, default='', max_length=255, verbose_name='SSH Anahtar Dosya Yolu')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='devices.device', verbose_name='Cihaz')),
            ],
            options={
                'verbose_name': 'Cihaz Kimlik Bilgisi',
                'verbose_name_plural': 'Cihaz Kimlik Bilgileri',
            },
        ),
    ]
