# Generated by Django 5.2.17 on 2026-08-16 12:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Görev Adı')),
                ('remote_path', models.CharField(default='/var/log', max_length=255, verbose_name='Uzak Sunucu Yolu')),
                ('local_destination', models.CharField(default='/backups', max_length=255, verbose_name='Yerel Yedekleme Dizini')),
                ('schedule', models.CharField(choices=[('HOURLY', 'Her Saat Başı'), ('DAILY', 'Her Gün (Gece 02:00)'), ('WEEKLY', 'Haftalık (Pazar 03:00)'), ('MANUAL', 'Manuel Tetikleme')], default='DAILY', max_length=20, verbose_name='Zamanlama')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('last_run_at', models.DateTimeField(blank=True, null=True, verbose_name='Son Çalışma Zamanı')),
                ('last_status', models.CharField(default='PENDING', max_length=20, verbose_name='Son Durum')),
                ('last_log', models.TextField(blank=True, default='', verbose_name='Son Çalışma Günlüğü')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_jobs', to='devices.device', verbose_name='Hedef Düğüm')),
            ],
            options={
                'verbose_name': 'Yedekleme & Eşitleme Görevi',
                'verbose_name_plural': 'Yedekleme & Eşitleme Görevleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
