# Generated by Django 5.2.17 on 2026-08-16 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_syncjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='connector_type',
            field=models.CharField(choices=[('WINDOWS_REMOTE', 'Windows Remote Management'), ('SSH', 'SSH / SFTP'), ('SFTP', 'SFTP Direct')], default='SSH', max_length=30, verbose_name='Bağlantı Türü'),
        ),
    ]
