# Generated by Django 5.2.17 on 2026-08-15 21:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Zaman Damgası')),
                ('username', models.CharField(blank=True, default='', max_length=150, verbose_name='Kullanıcı Adı')),
                ('user_role', models.CharField(blank=True, default='', max_length=50, verbose_name='Kullanıcı Rolü')),
                ('personnel_number', models.CharField(blank=True, db_index=True, default='', max_length=50, verbose_name='Sicil Numarası')),
                ('hostname', models.CharField(blank=True, db_index=True, default='', max_length=100, verbose_name='Cihaz Hostname')),
                ('operation', models.CharField(choices=[('LOGIN', 'Kullanıcı Girişi'), ('LOGOUT', 'Kullanıcı Çıkışı'), ('DEVICE_REGISTER', 'Cihaz Kaydı'), ('DEVICE_UPDATE', 'Cihaz Güncelleme'), ('DEVICE_DELETE', 'Cihaz Silme'), ('DEVICE_CONNECT_TEST', 'Bağlantı Testi'), ('LIST_DIR', 'Dizin Listeleme'), ('DOWNLOAD', 'Dosya İndirme'), ('UPLOAD', 'Dosya Yükleme'), ('DELETE_FILE', 'Dosya/Dizin Silme'), ('RENAME_FILE', 'Yeniden Adlandırma'), ('MOVE_FILE', 'Dosya Taşıma'), ('COPY_FILE', 'Dosya Kopyalama'), ('MKDIR', 'Klasör Oluşturma'), ('PREVIEW_FILE', 'Dosya Önizleme'), ('SAVE_FILE', 'Dosya Düzenleme/Kaydetme'), ('TRANSFER_START', 'Transfer Başlatıldı'), ('TRANSFER_COMPLETE', 'Transfer Tamamlandı'), ('TRANSFER_FAIL', 'Transfer Başarısız'), ('TERMINAL_SESSION', 'Terminal Oturumu'), ('TERMINAL_COMMAND', 'Terminal Komutu')], db_index=True, max_length=50, verbose_name='İşlem Türü')),
                ('path', models.CharField(blank=True, default='', max_length=1000, verbose_name='Dosya / Kaynak Yolu')),
                ('status', models.CharField(choices=[('SUCCESS', 'Başarılı'), ('FAILURE', 'Başarısız'), ('DENIED', 'Yetkisiz / Reddedildi')], db_index=True, default='SUCCESS', max_length=20, verbose_name='İşlem Durumu')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='İstemci IP Adresi')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Ek Güvenlik / Detay Bilgisi')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='devices.device', verbose_name='İlgili Cihaz')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Denetim Kaydı',
                'verbose_name_plural': 'Denetim Kayıtları',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp', 'operation'], name='audit_audit_timesta_39fbcd_idx'), models.Index(fields=['personnel_number', 'operation'], name='audit_audit_personn_30e472_idx'), models.Index(fields=['status', 'operation'], name='audit_audit_status_6e14c4_idx')],
            },
        ),
    ]
